# Python version to target
target-version = "py313"

select = [
  # Enable all rules
  "ALL",
]

ignore = [
  # Disable rules that might conflict with the formatter
  "COM812",
  "COM819",
  "D206",
  "D300",
  "E111",
  "E114",
  "E117",
  "E501",
  "ISC002",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "W191",

  # Disable rules that are too strict
  "ANN401",
  "ARG",
  "BLE",
  "D100",
  "D104",
  "D105",
  "D106",
  "D107",
  "DTZ",
  "S104",
]

[lint.extend-per-file-ignores]
# Disable some rules in tests
"tests/**" = [
  # Disable irrelevant rules
  "S",
]

[lint.isort]
known-first-party = [
  # Treat tests as a first-party module
  "tests",
]
